name: Deploy CloudFormation

on:
  workflow_dispatch:

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Configure Repo
        uses: actions/checkout@v4

      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v2
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: us-east-1

      - name: List Files
        run: ls -R
        working-directory: ${{ github.workspace }}

      - name: Deploy CloudFormation
        run: |
          aws cloudformation deploy \
          --stack-name DikshaFullStack \
          --template-file template.yml \
          --capabilities CAPABILITY_NAMED_IAM \
          --no-fail-on-empty-changeset

      - name: Get Outputs
        run: |
          aws cloudformation describe-stacks \
          --stack-name DikshaFullStack \
          --query "Stacks[0].Outputs[*].{Key:OutputKey,Value:OutputValue}" \
          --output text
      - name: Deploy CloudFormation
  run: |
          aws cloudformation deploy \
           --stack-name DikshaFullStack \
           --template-file template.yml \
           --capabilities CAPABILITY_NAMED_IAM \
           --no-fail-on-empty-changeset || true

             - name: Show Stack Events
        run: |
           aws cloudformation describe-stack-events \
           --stack-name DikshaFullStack \
           --max-items 20 \
           --output table
